# Generated by Django 3.2.13 on 2022-07-01 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0002_auto_20220630_1414'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='autor',
            new_name='author',
        ),
    ]
