# Generated by Django 3.2.13 on 2022-07-02 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0003_rename_autor_event_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='author',
            new_name='username',
        ),
    ]
